apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dbservice
spec:
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
        - name: dbservice
          image: dbservice
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 80
      protocol: TCP
  selector:
    app: dbservice